### ISSUE TITLE
Uppercase character minimum?

### ISSUE THREAD

**Issue by nebez** [alexis-anzieu-ssense/passense#1]
Great lib. I would like to enforce that valid passwords contain an uppercase character.

**Comment by alexis-anzieu-ssense** [comment]
Hello there, thank you!
Sure, I will work on this NASA feature asap

**Comment by alexis-anzieu-ssense** [comment]
https://github.com/alexissense/passense/commit/f7144b1157ded12f05d98ca92335a74022151d8c
