### ISSUE TITLE
Two different validations

### ISSUE THREAD

**Issue by nebez** [alexis-anzieu-ssense/passense#2]
Hi,

I use the validation library for two different types of logins:
* customers
* employees

For customers, I want to set different rules than for employees. Employees should have much stronger passwords because they get access to sensitive information.

How do I change the rules? Is it something you can support?

**Comment by alexis-anzieu-ssense** [comment]
Hey there,

You can now add a config object to your call and then edit it regarding your different validations.

Eg for a customer:
```js
const config =  {
    length: {
        minimum: 2
    }
}

passense.validatePassword("valid", config);
//=>true
```

Eg for an employee:
```js
const config =  {
    length: {
        minimum: 10
    },
    upperCase: {
        minimum: 3
    }
}

passense.validatePassword("This Is A Valid password", config);
//=>true
```
